# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0a2c7ae9906aa8b86f0450ac0e620e6fbdac5481bf61f54979fe10f3a0d67c807e9d49146b941bc3c7674b54221f96a5b9607c90487fd0733aa2e9705e48564

test:
  secret_key_base: ce7c9eb4ec36c27c425246067e78a9e90da33faece4aa5bfe9a7ee458183e9cdbed00cd926d69be6b29553e13d8783c3209f3c4c00f8e1afdc7406e642296d7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
